import {
  User,
  FileText,
  GraduationCap,
  Users,
  Clock,
  Calendar,
  DollarSign,
  Shield,
  TrendingUp,
  Package,
  Receipt,
  History,
  GitBranch,
  AlertTriangle,
  CreditCard,
  LogOut,
} from "lucide-react";

export const employeeTabs = [
  {
    id: "overview",
    label: "Overview",
    icon: User,
    description: "Basic information and quick stats",
  },
  {
    id: "documents",
    label: "Documents",
    icon: FileText,
    description: "Personal documents and files",
  },
  {
    id: "education",
    label: "Education",
    icon: GraduationCap,
    description: "Educational qualifications",
  },
  {
    id: "family",
    label: "Family",
    icon: Users,
    description: "Family and emergency contacts",
  },
  {
    id: "attendance",
    label: "Attendance",
    icon: Clock,
    description: "Attendance records and punches",
  },
  {
    id: "leaves",
    label: "Leaves",
    icon: Calendar,
    description: "Leave balance and history",
  },
  {
    id: "salary",
    label: "Salary",
    icon: DollarSign,
    description: "Salary structure and revisions",
  },
  {
    id: "statutory",
    label: "Statutory",
    icon: Shield,
    description: "PF, ESI, and compliance",
  },
  {
    id: "performance",
    label: "Performance",
    icon: TrendingUp,
    description: "Performance reviews and ratings",
  },
  {
    id: "assets",
    label: "Assets",
    icon: Package,
    description: "Assigned assets and equipment",
  },
  {
    id: "payroll",
    label: "Payroll",
    icon: Receipt,
    description: "Payslips and earnings",
  },
  {
    id: "loans",
    label: "Loans",
    icon: CreditCard,
    description: "Loans and advances",
  },
  {
    id: "warnings",
    label: "Warnings",
    icon: AlertTriangle,
    description: "Warnings and disciplinary actions",
  },
  {
    id: "timeline",
    label: "Timeline",
    icon: History,
    description: "Employment history timeline",
  },
  {
    id: "team",
    label: "Team",
    icon: GitBranch,
    description: "Reporting structure",
  },
  {
    id: "exit",
    label: "Exit",
    icon: LogOut,
    description: "Exit process and clearance",
  },
];
